# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Projeto Einstein
email: ejpixel@gmail.com
description: Aplicativo com versão web(acessível através de navegador) e versão para dispositivos móveis. O aplicativo permitirá ao professor registrar a presença dos alunos no momento da aula, aos alunos acompanhar sua frequência, e aos demais colaboradores do projeto Einstein competentes verificar assiduidade dos alunos a partir de relatórios gerados pelo sistema, com informações devidamente organizadas e apresentadas de forma que permita a identificação de problemas relacionados aos alunos, professores ou demais envolvidos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.ejpixel.com.br" # the base hostname & protocol for your site
github_username:  ejpixel

# Build settings
markdown: kramdown

include: ['_pages']
include: ['_telas']
